language: python

python:
  - "3.7"

dist: xenial

sudo: yes

services:
  - docker

before_install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  
  - docker-compose -f docker-compose-dev.yml build
  - docker-compose -f docker-compose-dev.yml up -d
  - docker ps -a